在某些情况下会出现ocr不到任何数据的情况，出现这个情况就返回个列表[None,None]]
03-Feb-24 20:37:07 - INFO - 判断任务HardQuest是否可以执行
03-Feb-24 20:37:07 - INFO - 执行任务HardQuest
03-Feb-24 20:37:07 - INFO - switch to hard quest
03-Feb-24 20:37:18 - INFO -   TCP    127.0.0.1:16512        0.0.0.0:0              LISTENING       18296
03-Feb-24 20:37:18 - INFO - 端口被占用，正在释放
03-Feb-24 20:37:19 - INFO - 端口被占用，已释放
03-Feb-24 20:37:19 - INFO - JP任务结束
Traceback (most recent call last):
  File "D:\github\BAAH1.2\BAAH.py", line 169, in BAAH_main
    my_AllTask.run()
  File "D:\github\BAAH1.2\modules\AllTask\myAllTask.py", line 68, in run
    task.run()
  File "D:\github\BAAH1.2\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "D:\github\BAAH1.2\modules\AllTask\InQuest\InQuest.py", line 54, in on_run
    HardQuest(hard_list_2).run()
  File "D:\github\BAAH1.2\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "D:\github\BAAH1.2\modules\AllTask\InQuest\HardQuest.py", line 42, in on_run
    jumpres = jump_to_page(to_page_num)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\BAAH1.2\modules\AllTask\InQuest\Questhelper.py", line 12, in jump_to_page
    return Task.run_until(
           ^^^^^^^^^^^^^^^
  File "D:\github\BAAH1.2\modules\AllTask\Task.py", line 132, in run_until
    if(func2()):
       ^^^^^^^
  File "D:\github\BAAH1.2\modules\AllTask\InQuest\Questhelper.py", line 14, in <lambda>
    lambda: ocr_area((122, 179), (165, 211))[0] == str(to_num),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\BAAH1.2\modules\utils\__init__.py", line 105, in ocr_area
    ocr_result = ocr_pic_area(f"./{get_config_screenshot_name()}", lowerpixel[0], lowerpixel[1], highterpixel[0], highterpixel[1])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github\BAAH1.2\modules\utils\image_processing.py", line 117, in ocr_pic_area
    rawImage = rawImage[fromy:toy, fromx:tox]
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred: